name: USTC Gym Appointment
on: 
  push:
    branches:
      - master
  schedule:
    - cron: '00 16 * * *'
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.6
        uses: actions/setup_python@v2
        with:
          python-version: 3.6
      - name: install requirements
        run: |
          sudo apt-get install tesseract-ocr
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run the script
        run: |
          python report.py
      
